// ngClient/src/app/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { Service } from '../services/service.service';
import { TokenManagerService } from '../../../projects/token-manager/src/public_api';
import { Router } from '@angular/router';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent implements OnInit {

  private email: string;
  private password: string;

  constructor(private service: Service, private router: Router) { }

  ngOnInit() {
  }

  login() {
    this.service.login({ email: this.email, password: this.password }).then(res => {
      const response = Object.assign({ access_token: '', expires_in: '' }, res);
      TokenManagerService.setTokenWithExpiration(response.access_token, Number.parseInt(response.expires_in));

      const headerObj = {
        'Content-Type': 'application/json',
        'authorization': 'Bearer ' + sessionStorage.getItem('token')
      };
      this.service.setAuthHeader(headerObj);
      this.router.navigate(['test-auth']);
    }).catch(error => console.log(error));
  }

}

<div class="container">
  <div class="form-group">
    <label for="">Email</label>
    <input type="text" [(ngModel)]="email" class="form-control">
  </div>
  <div class="form-group">
    <label *ngIf="role == 'admin'" for="">Password</label>
    <input type="password" [(ngModel)]="password" class="form-control">
  </div>
  <div class="form-group">
    <button class="btn btn-primary" (click)="login()">LOGIN</button>
  </div>
</div>

// client/src/components/Login.vue
<template>
    <div class="container">
        <h1>Login</h1>
        <form @submit.prevent="login">
            <div class="form-group">
                <label for="">Email</label>
                <input type="text" v-model="email" class="form-control">
            </div>
            <div class="form-group">
                <label for="">Password</label>
                <input type="password" v-model="password" class="form-control">
            </div>
            <div class="form-group">
                <button class="btn btn-primary" type="submit">Login</button>
                <router-link :to="{name:'Register'}">Register</router-link>
            </div>
            <div class="form-group" v-if="error !== ''">
                <div class="alert alert-danger">{{error}}</div>
            </div>
        </form>
    </div>
</template>
<script>
import service from "../service/index";
export default {
  data() {
    return {
      email: "",
      password: "",
      msg: "",
      error: ""
    };
  },
  methods: {
    login() {
      const _this = this;
      service
        .login({ email: this.email, password: this.password })
        .then(res => {
          this.$auth.setToken(
            res.endpointResult.token_type +
              " " +
              res.endpointResult.access_token,
            res.endpointResult.expires_in + Date.now()
          );
          this.error = "";

          window.location.reload();
        })
        .catch(error => {
          this.error = "Wrong email/password";
        });
    }
  }
};
</script>
